<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>async / await</title>
</head>
<body>

  <button id="btn">성공판정</button>

  <script>
    async function 더하기(){
      var 프로미스 = new Promise(function(resolve, reject){
        var 힘든연산 = 1 + 1;
        // resolve(힘든연산);
        reject(힘든연산);
      });


      // await은 프로미스 실패시 에러나고 멈춤 -> 방지하기 위해 try{} catch{} 사용
      try {
        var 결과 = await 프로미스; // 프로미스가 해결될 때까지 기다림(동기적) | await은 프로미스 실패시 에러나고 멈춤
        console.log(결과);
      } catch {
        console.log('프로미스 연산이 잘 안되었군요');
      }

      /* 프로미스.then(function(){
        console.log("성공했어요");
      }); */

      // return Promise.reject('실패임'); -> 실패시 실행
    }

    더하기();

    /* async
    - 함수 앞에만 붙일 수 있음
    - 함수 실행 후에 Promise 오브젝트가 남음(new Promise() 디자인 안하고, async만 붙이면 됨)
    - 'return 연산결과'라고 쓰면 then의 parameter로 데이터 전달 가능
    - 성공만 가능 -> 실패를 사용하려면? 'return Promise.reject('실패임')'
    */

    /* 더하기().then(function(result){
      // console.log("성공이에요");
      console.log(result); // 2(연산결과)
    }); */



    // Q. <button>을 누르면 성공 판정하는 Promise 만들기 + 성공시 "성공했어요" 출력하기
      async function success(){
        var 프로미스2 = new Promise((resolve, reject) => {
            document.querySelector("#btn").addEventListener("click", () => {
            resolve("성공했어요");
          });
        });

        try {
          var result = await 프로미스2;
          console.log(result);
        } catch {
          console.log("실패했어요");
        }
      }

      success();


  </script>
</body>
</html>